### ISSUE TITLE
Nombre del archivo ZIP no es correo

### ISSUE THREAD

**Issue by jabarreto** [thegreenter/demo#100]
Cuando envío una guia de remisión remitente me sale el siguiente error: 

El nombre del archivo ZIP es incorrecto - Detalle: xxx.xxx.xxx value='ticket: 2020005445824780000 error: Comprobante no valido para este receptor. codigo cpe: "09" UBL version: "2.1" no es un cpe valido'
Pero el nombre de archivo zip esta bien.

Algunos de ustedes le ha pasado.

**Comment by giansalex** [comment]
Hola @jabarreto , creo que un mensaje similar aparece cuando se envia un comprobante a un URL de servicio que no le corresponde.
