### ISSUE TITLE
ERROR EN FECHA DE COMUNICACION DE BAJAS

### ISSUE THREAD

**Issue by J0rg38** [thegreenter/demo#101]
Hola, estoy queriendo generar la baja de algunos comprobantes y al momento de procesarla me salta el error **2346: La fecha de generación del resumen debe ser igual a la fecha consignada en el nombre del archivo**  estoy dandome cuenta de que al colocar la fecha en ->setFecComunicacion(new \DateTime('2020-11-04')) cuando genera el XML le coloca una fecha antes siendo el 2020-11-03, como podria solucionarlo.

**Comment by giansalex** [comment]
Hola @J0rg38 , podrías obtener la zona horaria desde donde estas haciendo el envio.

```php
<?php

if (date_default_timezone_get()) {
    echo 'date_default_timezone_set: ' . date_default_timezone_get() . '<br />';
}

if (ini_get('date.timezone')) {
    echo 'date.timezone: ' . ini_get('date.timezone');
}
```

**Comment by J0rg38** [comment]
Perfecto, funciono editando el archivo init de PHP con las zona horaria

**Comment by giansalex** [comment]
@J0rg38 usas una ultima version  `greenter`?, porque se habia agregado una [configuración de zona horaria](https://github.com/thegreenter/greenter/releases/tag/v4.0.2) para evitar depender de la configuracion de php.

**Comment by J0rg38** [comment]
Si, acabo de descargar el codigo el dia de ayer, igual actualizo los paquetes.
