### ISSUE TITLE
Facturacion Colombia

### ISSUE THREAD

**Issue by DD4F** [thegreenter/demo#102]
Hola estoy me prodria ayudar para facturacion electronica en colombia ? Gracias

**Comment by giansalex** [comment]
Hola @DD4F , tal vez estos paquetes que son mas genéricos
- [xmldsig](https://github.com/thegreenter/xmldsig), firma digital
- [ubl-validator](https://github.com/thegreenter/ubl-validator), validar esquema UBL
- [ubl-classes](https://github.com/thegreenter/xml-serializer), ejemplo de UBL 2.1 a php objects 

> En general, esta proyecto esta hecho para la facturacion electronica en Perú
