### ISSUE TITLE
error \SoapClient.php on line 19

### ISSUE THREAD

**Issue by omarx33** [thegreenter/demo#103]
Hola compañeros programadores, soy nuevo usando greenter, descargue el demo y al ejecutar una factura u otro documento me sale este error. agradezco su ayuda de antemano.
![Captura](https://user-images.githubusercontent.com/42531886/104083673-8b003b00-520e-11eb-81f2-25f4a88bc78c.PNG)

**Comment by giansalex** [comment]
Hola @omarx33 , tienes que activar la extension `soap` en `php.ini`
