### ISSUE TITLE
error fetching http headers, en resúmenes

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [thegreenter/demo#106]
Buenas noches, estaba probando en local los resúmenes diarios y me sale el error:  error fetching http headers, lo probe en en el demo de heroku y sale el error de la imagen.
![image](https://user-images.githubusercontent.com/31812268/108651098-0f411180-748f-11eb-9765-33f80c2ccb73.png)

**Comment by giansalex** [comment]
Volviendo a verificar, el método `getStatus` del servicio beta es el que no responde.

**Comment by giansalex** [comment]
Hola @JHONQUISPEFLORES , acabo de verificar que ya esta activo el servicio de SUNAT para resumen y c. de bajas.
