### ISSUE TITLE
status-cdr.php  ticket no existe

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [thegreenter/demo#108]
Buenas noches, una consulta porque en todas las consultas para el CDR me sale el mensaje ticket no existe. si consulto ese mismo documento desde la página de la sunat y esta como aceptada?????
Probe con el usuario principal y secundario, pero igual me sale ese mensaje "El ticket no existe", quizas sepas el porque pueda ser??
![image](https://user-images.githubusercontent.com/31812268/118347229-3431a780-b507-11eb-8aae-ab0a458a1440.png)

**Comment by giansalex** [comment]
@JHONQUISPEFLORES tal vez es un error del servicio de SUNAT, la semana pasada informaron de problemas.
