### ISSUE TITLE
Baja de Guias de Remision

### ISSUE THREAD

**Issue by malc32** [thegreenter/demo#116]
Creo que no se puede hacer la baja de una guia de remision por el facturador, llame a la sunat y me dijeron que solo se puede hacer por la pagina web de la sunat, en resumen creo que el archivo [guia-remision-baja.php](https://github.com/thegreenter/demo/blob/master/examples/guia-remision-baja.php) no esta correcto, me confirmas si me equivoco, gracias, y muy buen trabajo

**Comment by giansalex** [comment]
Segun las validaciones solo se puede para el caso: `baja por cambio de destinatario`

**Comment by giansalex** [comment]
Con el nuevo formato de guia, esto ya no es posible.
