### ISSUE TITLE
Monto de percepción no coincide con el total a pagar, debería ser 2.38?

### ISSUE THREAD

**Issue by willianmzc** [thegreenter/demo#119]
https://github.com/thegreenter/demo/blob/e358fe07c1ecccb172206c4e36582db397b1d0ff/examples/resumen.php#L58C20-L58C20

**Comment by giansalex** [comment]
Fue corregido aqui  https://github.com/thegreenter/demo/commit/19b6afeba5f9dba389fc377e519f26ff26b30117
