### ISSUE TITLE
Envio de Guia Remision Electronica

### ISSUE THREAD

**Issue by jose1894** [thegreenter/demo#121]
Buenas tardes,

Antes que nada y como siempre, dando las gracias por el apoyo.

He seguido al pie de la letra el procedimiento para poder loguearme al API Rest de la Sunat mediante esta libreria, y funciona perfectamente.

Pero cuando hago el envio de la guia electronica, especificamente aqui:

![image](https://github.com/thegreenter/demo/assets/12040206/b413aa81-8adb-415a-a951-3f8cc1718722)

 Me devuelve un error, que es el siguiente:

![image](https://github.com/thegreenter/demo/assets/12040206/a70a1876-52d7-43a2-b07e-b2b31ed618a2)

No se que hacer con respecto a eso.

Agradeciendo de antemano toda la colaboracion! Saludos.

**Comment by giansalex** [comment]
Hola, has configurado tus propias credenciales?

**Comment by jose1894** [comment]
Hola, si por supuesto. Me autentico bien, pero cuando hace el envío me da
ese error.

Saludos

**Comment by jose1894** [comment]
Buenos dias,

Te muestro las credenciales configuradas segun el manual de la SUNAT.

![image](https://github.com/thegreenter/demo/assets/12040206/fa9f7971-dda2-4c72-9b1d-569566131d8e)

**Comment by jose1894** [comment]
Hola!,

Ya pude resolver la conexion hacia falta el "v1" en la ruta "https://api-cpe.sunat.gob.pe"

Ahora me devuelve una respuesta con el codigo  98

Gracias
