### ISSUE TITLE
127 El ticket no existe, pero sí existe.

### ISSUE THREAD

**Issue by thefantas** [thegreenter/demo#74]
@djdnl13 segun lo que dice @Redlein guarda el ticket, consulta la primera vez y le retorna codigo 98, vuelve a consultar y le aparece el mensaje de "No existe el ticket". También creo que una forma de evitarlo seria dando mas tiempo antes de consultar.

_Originally posted by @giansalex in https://github.com/giansalex/greenter-sample/issues/60#issuecomment-485294321_

Hola, que pena abrir el post, pero es un tema muy parecido.
Sunat logra dar un ticker a un RA o RC, (ejm, 3000000X93X94X5) pero al consulta, 127 no existe el ticket.. o sea, el problema ya no es que no te de un ticket sino que te da uno que no es el correcto, ya que posteriormente en el portal de SUNAT reviso la baja de ese documento y se ejecutó correctamente pero con un ticket totalmente distinto (ejm,  201909612992649), que al actualizar el ticket en la consulta obtengo la respuesta deseada, que existe y ha sido aceptada.

La consulta es, cómo obtener el ticket correcto? hay alguna forma de automatizarlo? ya que por ahora se hace manualmente, estoy seguro a más de uno le ha pasado.

Saludos.

**Comment by MrJmpl3** [comment]
Se ha informado ese error a SUNAT y via telefonica aceptaron que tienen ese error, pero no hay emitido comunicado eso.

Administro una grupo de Facebook donde parece ser que ese error ocurre en algunas empresas y en diferentes sistemas no solo el de greenter.

**Comment by thefantas** [comment]
Lástima que el servidor de SUNAT esté muy mal, ahora mismo al consultar el ticket 2019 me dice que tampoco existe, y es cierto lo que comentas, algunas empresas envío y recibo CDR de aceptación pero al consultar el documento en el portal de SUNAT simplemente no existe.

**Comment by giansalex** [comment]
Se supone que el ticket que devuelve sunat debe ser el correcto. No he visto algún servicio que retorne el numero del ticket, aunque si puedes encontrarlo dentro de sunat podrías hacer scrapping

**Comment by thefantas** [comment]
Lo malo que SUNAT por cada petición correcta te muestra 50 not found y lo hace poco alentador.
