### ISSUE TITLE
Resumenes diarios me arrojan un código de error HTTP

### ISSUE THREAD

**Issue by devrheber** [thegreenter/demo#78]
Buenas tardes.
Estoy teniendo problemas con los resumenes diarios:
El error que recibo es este: Service Temporarily Unavailable

Cuando verifico en la página de ejemplo subida a Heroku, no hay ningún problema, pero intentando enviarla desde mi servidor si tengo problemas.

Estoy usando el modo Beta y la verdad no se que pueda estar pasando.

**Comment by giansalex** [comment]
Hola @devrheber , tal vez esto te pueda ayudar https://github.com/giansalex/greenter/issues/83#issuecomment-510624880

**Comment by devrheber** [comment]
Intenté agregando esos parametros para deshabilitar la verificación, pero aún sigo recibiendo el mismo problema.

**Comment by giansalex** [comment]
Si retorna una respuesta, entonces puede ser que la url tal vez no sea la correcta.

**Comment by giansalex** [comment]
Este error es el mismo que https://github.com/thegreenter/demo/issues/82#issuecomment-631549641
