### ISSUE TITLE
Consulta de ticket de modo prueba

### ISSUE THREAD

**Issue by brandon305** [thegreenter/demo#82]
Saludos , este es el código que estoy probando para dar de baja a una factura , no tengo problemas con la generación del xml y me muetra un ticket , pero en la función getStatus($ticket) me devuelve el mensaje 'Service Temporarily Unavailable' .... es esto normal porque no estoy en producción o algo estoy fallando en mi código.

`<?php

use Greenter\Model\Client\Client;
use Greenter\Model\Company\Company;
use Greenter\Model\Company\Address;
use Greenter\Model\Sale\Invoice;
use Greenter\Model\Sale\SaleDetail;
use Greenter\Model\Sale\Legend;

use Greenter\Model\Voided\Voided;
use Greenter\Model\Voided\VoidedDetail;
use Greenter\Ws\Services\SunatEndpoints;
use Greenter\Ws\Services\ConsultCdrService;
use Greenter\Ws\Services\SoapClient;

require __DIR__ . '/vendor/autoload.php';
$see = require __DIR__.'/config.php';

// Emisor
$address = new Address();
$address->setUbigueo('150101')
    ->setDepartamento('LIMA')
    ->setProvincia('LIMA')
    ->setDistrito('LIMA')
    ->setUrbanizacion('NONE')
    ->setDireccion('AV LS');

$company = new Company();
$company->setRuc('20000000001')
    ->setRazonSocial('EMPRESA SAC')
    ->setNombreComercial('EMPRESA')
    ->setAddress($address);

$detial1 = new VoidedDetail();
$detial1->setTipoDoc('01')
    ->setSerie('F001')
    ->setCorrelativo('1')
    ->setDesMotivoBaja('ERROR EN CÁLCULOS');

$voided = new Voided();
$voided->setCorrelativo('00112')
    ->setFecGeneracion(new \DateTime('-3days'))
    ->setFecComunicacion(new \DateTime('-1days'))
    ->setCompany($company)
    ->setDetails([$detial1]);

$result = $see->send($voided);

// Guardar XML
file_put_contents($voided->getName().'.xml',
                  $see->getFactory()->getLastXml());
if (!$result->isSuccess()) {
    var_dump($result->getError());
    exit();
}

$ticket = $result->getTicket();
echo 'Ticket :<strong>' . $ticket .'</strong>';

$result = $see->getStatus($ticket);
if (!$result->isSuccess()) {
    var_dump($result->getError());
    return;
}

$result = $see->getStatus($ticket);
print_r($result);
`

**Comment by giansalex** [comment]
Hola @brandon305, a veces puede ocurrir eso, lo servicios de sunat pueden estar inactivos. Vuelve a intentar.

**Comment by brandon305** [comment]
Hoy volví a probar y la sunat me sigue devolviendo 'Service Temporarily Unavailable' en $see->getStatus($ticket);

Entonces es error de los servicios de ellos ? , ya que si me devuelve un número de ticket antes de consultar su estado.

**Comment by giansalex** [comment]
Es raro, por que en el [demo live](https://greenter-sample.herokuapp.com/), no ocurre es problema.
Estas probando desde windows o linux?

**Comment by brandon305** [comment]
Lo que quiero dar de baja es una factura , por eso es $detial1->setTipoDoc('01')  , correcto ?

**Comment by giansalex** [comment]
Si, ese es el tipo para factura.
Prueba este codigo.
```php
<?php

require 'vendor/autoload.php';

use Greenter\Ws\Services\SoapClient;
use Greenter\Ws\Services\ExtService;

$urlService = 'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService';
$soap = new SoapClient();
$soap->setService($urlService);
$soap->setCredentials('20000000001MODDATOS', 'moddatos'); 
$sender = new ExtService();
$sender->setClient($soap);

$result = $sender->getStatus('1589988459441');

print_r($result);
```
Deberia retornarte un codigo de error `0127`.

**Comment by brandon305** [comment]
exacto me reporto ese error , entonces en que estoy fallando :( , en mi codigo

**Comment by giansalex** [comment]
No me percate, pero estas llamando 2 veces `getStatus`, borra la ultima linea `$result = $see->getStatus($ticket);
`

**Comment by brandon305** [comment]
claro eso ya lo borre , pero ese error lo bota en 
if (!$result->isSuccess()) {
var_dump($result->getError());
return;
}

**Comment by giansalex** [comment]
He probado en varios lados y no tengo ese problema, verifica que estés usando esta url de servicio `https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService` y si persite también verifica si aparece ese problema levantando la [demo](https://github.com/thegreenter/demo)

**Comment by brandon305** [comment]
Al final hice un híbrido de nuestros dos códigos jeje  y salio.  Estaba usando esto config.php
$see = new See();
$see->setService(SunatEndpoints::FE_BETA);
$see->setCertificate(file_get_contents(__DIR__.'/certificate.pem'));
$see->setCredentials('20000000001MODDATOS'/*ruc+usuario*/, 'moddatos');

en tu código ya no este necesario poner el certificado en tu variable $soap , no ? 
bueno comparto mi código final , aunque esta desordenado , pero es para ir haciendo pruebas 

`<?php

use Greenter\Model\Client\Client;
use Greenter\Model\Company\Company;
use Greenter\Model\Company\Address;
use Greenter\Model\Sale\Invoice;
use Greenter\Model\Sale\SaleDetail;
use Greenter\Model\Sale\Legend;

use Greenter\Model\Voided\Voided;
use Greenter\Model\Voided\VoidedDetail;
use Greenter\Ws\Services\SunatEndpoints;
use Greenter\Ws\Services\ConsultCdrService;
use Greenter\Ws\Services\SoapClient;
use Greenter\Ws\Services\ExtService;

require __DIR__ . '/vendor/autoload.php';
$see = require __DIR__.'/config.php';

// Emisor
$address = new Address();
$address->setUbigueo('150101')
    ->setDepartamento('LIMA')
    ->setProvincia('LIMA')
    ->setDistrito('LIMA')
    ->setUrbanizacion('NONE')
    ->setDireccion('AV LS');

$company = new Company();
$company->setRuc('20000000001')
    ->setRazonSocial('EMPRESA SAC')
    ->setNombreComercial('EMPRESA')
    ->setAddress($address);


$detial1 = new VoidedDetail();
$detial1->setTipoDoc('01')
    ->setSerie('F001')
    ->setCorrelativo('1')
    ->setDesMotivoBaja('ERROR EN CÁLCULOS');


$voided = new Voided();
$voided->setCorrelativo('00112')
    ->setFecGeneracion(new \DateTime('-3days'))
    ->setFecComunicacion(new \DateTime('-1days'))
    ->setCompany($company)
    ->setDetails([$detial1]);

$result = $see->send($voided);

// Guardar XML
file_put_contents($voided->getName().'.xml',
                  $see->getFactory()->getLastXml());
if (!$result->isSuccess()) {
    var_dump($result->getError());
    exit();
}

$ticket = $result->getTicket();
echo 'Ticket :<strong>' . $ticket .'</strong>';

$urlService = 'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService';
$soap = new SoapClient();
$soap->setService($urlService);
$soap->setCredentials('20000000001MODDATOS', 'moddatos'); 
$sender = new ExtService();
$sender->setClient($soap);

$result = $sender->getStatus($ticket);
if (!$result->isSuccess()) {
    var_dump($result->getError());
    return;
}

echo $result->getCdrResponse()->getDescription();
file_put_contents('R-'.$voided->getName().'.zip', $result->getCdrZip());`

**Comment by giansalex** [comment]
El certificado es solo para firmar el XML, para soap solo se necesita credenciales (clave SOL).
