### ISSUE TITLE
En el setCodProducto iria un codigo interno o codProducto segun Sunat?

### ISSUE THREAD

**Issue by jhuniors2111** [thegreenter/demo#83]
Estaba leyendo un poco pero me confunde,
En sunat dice que no es tan olbigatorio el codproducto : https://cpe.sunat.gob.pe/informacion_general/codigoproducto
Sin embargo en muchos artículos dicen que es obligatorio, como en este. https://www.realsystems.com.pe/noticias/exigencia-consignar-codigo-productos-sunat .
En conclusión no se si poner un código interno o un código según relacionado con la lista de códigos de productos sunat.

**Comment by giansalex** [comment]
Hola @jhuniors2111 existe un campo para cada codigo.
- `setCodProducto`: codigo interno
- `setCodProdSunat`: codigo producto SUNAT

Según esa nota, seria obligatorio para todos a partir del siguiente año, aunque puedes enviarlo sin problema, trataré de incluir el codProductoSunat en los ejemplos.

**Comment by jhuniors2111** [comment]
Gracias por la aclaración.
