### ISSUE TITLE
El setSubTotal es el total de la venta sin impuesto?

### ISSUE THREAD

**Issue by jhuniors2111** [thegreenter/demo#84]
Buenas cuando ejecuto tu ejemplo de boletas.php me sale un error `string(81) "4317 - Debe consignar el Total Precio de Venta - INFO: 4317 (nodo: "/" valor: "")"` ..
Ahora cuando le pongo el ->setSubTotal(118) la respuesta es correcta.. pero ese monto es el valor de la venta mas IGV
el subTotal no seria 100 ya que es el monto sin IGV
[DATOS DEL EJEMPLO ](https://github.com/thegreenter/demo/blob/master/examples/boleta.php) 
DATOS DEL EJEMPLO : https://github.com/thegreenter/demo/blob/master/examples/boleta.php 
 
O cual seria el error, por que con mis datos que yo le paso me sale el mismo error de consignar el total precio de venta
Este es mi código lo que esta comentado al costado de la variable son los valores que recibe, en el detalle solo paso un producto
![image](https://user-images.githubusercontent.com/22435668/87097890-c4c69980-c20b-11ea-85a9-689d8409af37.png)

Cuando ejecuto en el setSubTotal me sale este error 
![image](https://user-images.githubusercontent.com/22435668/87098006-fb9caf80-c20b-11ea-8339-eef781c6722d.png)

y cuando le pongo el ->setSubTotal(1057.50)  el comprobante lo recibo correctamente...
Pero como te decía el subtotal es el valor de venta sin igv, la cual tendría que poner ->setSubTotal(896.19), pero cuando pongo esto sale 2 errores "4312 - El importe total del comprobante no coincide con el valor calculado" , ""4310 - La sumatoria del Total del valor de venta más los impuestos no concuerda con la base imponible"..
O es otra variable que va?

**Comment by giansalex** [comment]
Eso fue algo que se corrigió en el ejemplo de factura, para el caso de Boleta este se envía usando el Resumen Diario no individualmente como las facturas.

**Comment by jhuniors2111** [comment]
En caso de la factura el subtotal seria el monto total con Igv o es el monto sin IGV?

**Comment by giansalex** [comment]
Seria con IGV, generalmente es igual al Importe Venta, cuando no es una factura de anticipo.

**Comment by jhuniors2111** [comment]
> Eso fue algo que se corrigió en el ejemplo de factura, para el caso de Boleta este se envía usando el Resumen Diario no individualmente como las facturas.

Con respecto a esto, en las boletas debe ir el hash del xml, no haria el envio a la sunat de la boleta. pero puedo sacar  el hash del xml getHashSign , ya después los envió todo con resumen cierto.
lo digo por que en las boletas impresas siempre va el QR con el hash del xml y datos de la boleta

**Comment by giansalex** [comment]
Si, de todas formas se tienen que generar los xml firmado, y estar disponible para el receptor.

> PD: Se agregó el campo que faltaba en el ejemplo de boleta 7bc32bfb94264f947ec587f0db1ee3bef4f0475d

**Comment by jhuniors2111** [comment]
> Si, de todas formas se tienen que generar los xml firmado, y estar disponible para el receptor.
> 
> > PD: Se agregó el campo que faltaba en el ejemplo de boleta [7bc32bf](https://github.com/thegreenter/demo/commit/7bc32bfb94264f947ec587f0db1ee3bef4f0475d)

Gracias ... una ultima consulta para sacar el hash xml todavía tengo que instalar la librería greenter/report para usar solo el getHashSign , o hay otra opción sin instalar la librería.

**Comment by giansalex** [comment]
De momento si, o sino podrías copiar la clase [XmlUtils](https://github.com/thegreenter/report/blob/master/src/Report/XmlUtils.phpl) a tu repositorio, tal vez después se podría separar e incluirla en una librería aparte como herramientas de xml.
