### ISSUE TITLE
Consulta: Comunicación de Baja y Resumen diario (Estado y tiempo limite de envio) 

### ISSUE THREAD

**Issue by jhuniors2111** [thegreenter/demo#88]
Cuando se hace una comunicación de baja o un resumen con estado 3 de las boletas, esos correlativos ya no se usarían entonces, de igual manera la comunicación de baja solo tiene plazo de 7 días para generar como el envió de resumen o no hay plazo ahí?

**Comment by giansalex** [comment]
Si, generalmente el limite es de 7 días, aunque también se puede manejar como se hacia con las facturas físicas, usando notas de crédito / débito, que creo que es la unica forma que existe cuando se emite desde el Portal de Sunat.

**Comment by jhuniors2111** [comment]
Cuando se usa con el SEE si genera el correlativo Ejemp B001-1 y lo quiere mandar con estado 3 que es eliminar, entonces después que genero otra boleta usuario otro correlativo B001-2, o tengo que enviar de nuevo el B001-1 con otros datos?

**Comment by giansalex** [comment]
Tiene que enviarse otra Boleta, ese correlativo ya no se puede utilizar, si consultas en Validez CPE de sunat te aparecerá como dado de baja.

**Comment by jhuniors2111** [comment]
mm una consulta mas, lo que pasa que había hecho una tarea programada para que se envíen resúmenes diarios cada cierto tiempo, pero ahora que me fijo no se han enviado comprobantes hace 13 dias, crees que se pueda enviar el resumen o hay otra forma de enviarlos?

**Comment by giansalex** [comment]
Creo que si, puedes intentarlo; para el caso del resumen diario los limites de tiempo no estaban tan definidos.
