### ISSUE TITLE
Descuento Lineal

### ISSUE THREAD

**Issue by sosviper** [thegreenter/demo#90]
Saludos cordiales
Tienes algun ejemplo de descuento lineal con sumatoria total de todas las lineas. 
**Nota**: Es diferente al descuento Global, porque hasta donde se, el descuenot Global afecta la Base Imponible. Pero el descuento por linea como deberia de ser.
Por ejemplo tengo lo siguiente: 
```
Cantidad      Precio           Precio con Descuento(40%)                Descuento              Subtotal 
    6                44.8                    26.88                        107.52                   161.28
    2                44.8                    26.88                        35.84                    53.76
    7                44.8                    26.88                        125.44                   188.16 
    4                44.8                    26.88                         71.68                   107.52
    4                44.8                    26.88                         71.68                   107.52 
    3                44.8                    26.88                         53.76                    80.64 
    5                33.0                     19.80                         66.00                    99.00
    4                44.8.                    26.88                         71.68                   107.52
                                            TOTAL DESCUENTO.              603.60
                                             OP GRAVADA.                                            905.40
                                              IGV.                                                 162.97
                                              TOTAL.                                              1068.37
```

**Comment by giansalex** [comment]
Hola @sosviper , el descuento global o por linea puede afectar o no a la base imponible.
![image](https://user-images.githubusercontent.com/14926587/89074611-4197ef80-d342-11ea-82c1-4aa88ab2af40.png)

**Comment by sosviper** [comment]
Hola , me puedes orientar como debe ser el archivo xml o ubl 2.1 porque en los ejemplos solo hay con descuento Global, pero en este caso quisiera saber con descuento por item pero con codigo 00. Tambien quisiera saber si es necesario agregarle el totsal de todos los descuentos y si fuese el caso como seria el archivo XML. En estos momentos estoy utilizando el demo que tiene ejemplos, pero no encuentro el ejemplo con descuento por linea, solo hay por Descuento Global.

**Comment by giansalex** [comment]
Puedes encontrar un ejemplo [aquí](https://github.com/thegreenter/demo/blob/migrate-greenter-4.0/examples/factura-descuento-linea.php).
